# -*- coding: utf-8 -*-
"""stroke_detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XgiFtX1IoxEKtp4FwJBiG71D_SsysYV8
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("/content/healthcare-dataset-stroke-data.csv")
print (data.head())

data.tail()

data.info()

print(data[['smoking_status','gender','ever_married','work_type','Residence_type']].dtypes)

data.describe()

data.shape

data.columns

data.isnull().sum()

data['bmi']=data['bmi'].fillna(data['bmi'].median())

data.isnull().sum()

data.dropna()

conditional_bmi=data[data['bmi']<=25.5]
print(conditional_bmi.head())

conditional_smoking_status=data[data['smoking_status']!='never smoked']
print(conditional_smoking_status)

conditional_smokingstatus=data[data['smoking_status'].isin(['formerly smoked','smokes'])]
print(conditional_smokingstatus)

data["smoking_status"].value_counts().plot(kind="bar")
plt.title("Bar Plot")
plt.xlabel("smoking_status")
plt.ylabel("Count")
plt.show()

plt.hist(data["avg_glucose_level"],bins=20)
plt.title("Histogram")
plt.xlabel("avg_glucose_level")
plt.ylabel("Count")
plt.show()

#peichart

data["smoking_status"].value_counts().plot(kind="pie",autopct="%0.1f%%")
plt.title("Pie chart")
plt.show()

data.iloc[:,5:12].plot(kind="box")
plt.title("Box plot")
plt.show()

#seaborn

sns.histplot(data['avg_glucose_level'])
plt.show()

sns.boxplot(x="smoking_status",y="age",data=data)
plt.show()

sns.violinplot(x="smoking_status",y="avg_glucose_level",data=data)
plt.show()

sns.scatterplot(x="work_type",y="bmi",hue="age",data=data)
plt.show()

sns.pairplot(data,hue="smoking_status")
plt.show()

sns.countplot(x="smoking_status",data=data)
plt.show()